version: '3'
services:
  php:
    platform: linux/amd64
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./vhosts/msdn.miet.ru/:/srv/vhosts/msdn.miet.ru/:ro
    network_mode: "host"

  nginx:
    platform: linux/amd64
    image: nginx:1.24
    restart: always
    volumes:
      - ./nginx-root-configs/abit-htpasswd:/etc/nginx/abit-htpasswd:ro
      - ./nginx-root-configs/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./nginx-root-configs/geo.conf:/etc/nginx/geo.conf:ro
      - ./nginx-root-configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs/:/etc/nginx/cert/:ro
      - ./nginx-logs/:/var/log/nginx/:rw
      - ./vhosts/:/srv/vhosts/:ro
      - ./vhosts/msdn.miet.ru/nginx.conf:/etc/nginx/conf.d/msdn.miet.ru.conf:ro
      - ./vhosts/msdn.miet.ru/:/srv/vhosts/msdn.miet.ru/:ro
    extra_hosts:
      - "php:127.0.0.1"
    depends_on:
      - php
    network_mode: "host"
