name: CI/CD Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Install rsync and sync files
        run: |
          # ставим rsync
          sudo apt-get update && sudo apt-get install -y rsync
          # проверяем, что rsync в PATH
          which rsync
          rsync --version

          rsync -az --delete \
            --exclude="nginx-pagespeed-cache/*" \
            --exclude="nginx-logs/*" \
            --exclude=".*" \
            ./ "${{ secrets.RP_CONNECTION_STRING }}":/srv/miet-rp

      - name: Reload Nginx on server
        run: ssh "${{ secrets.RP_CONNECTION_STRING }}" 'cd /srv/miet-rp && ./update.sh'

  recreate:
    name: Recreate Containers (manual)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - run: ssh "${{ secrets.RP_CONNECTION_STRING }}" 'cd /srv/miet-rp && ./recreate.sh'
