# .github/workflows/deploy.yml

name: CI/CD Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Install rsync locally
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Rsync to server
        run: |
          rsync -az --delete \
            --exclude="nginx-pagespeed-cache/*" \
            --exclude="nginx-logs/*" \
            --exclude=".*" \
            ./ "${{ secrets.RP_CONNECTION_STRING }}":/srv/miet-rp

      - name: Ensure Docker & Compose on remote
        run: |
          ssh "${{ secrets.RP_CONNECTION_STRING }}" \
            "command -v docker >/dev/null || (sudo apt-get update && sudo apt-get install -y docker.io docker-compose)"

      - name: Deploy containers on remote
        run: |
          ssh "${{ secrets.RP_CONNECTION_STRING }}" << 'EOF'
            cd /srv/miet-rp
            docker-compose pull
            docker-compose up -d
          EOF

      - name: Wait for nginx container
        run: |
          ssh "${{ secrets.RP_CONNECTION_STRING }}" << 'EOF'
            cd /srv/miet-rp
            for i in $(seq 1 60); do
              cid=$(docker-compose ps -q nginx)
              if [ -n "$cid" ] && [ "$(docker inspect -f '{{.State.Status}}' "$cid")" = "running" ]; then
                exit 0
              fi
              sleep 1
            done
            echo "nginx container did not start in time" >&2
            exit 1
          EOF

      - name: Reload nginx in container
        run: |
          ssh "${{ secrets.RP_CONNECTION_STRING }}" \
            "cd /srv/miet-rp && docker-compose exec -T nginx nginx -s reload"
