# .github/workflows/deploy.yml
name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Rsync to server
        run: |
          rsync -az --delete \
            --exclude="nginx-pagespeed-cache/*" \
            --exclude="nginx-logs/*" \
            --exclude=".*" \
            ./ "${{ secrets.RP_CONNECTION_STRING }}":/srv/miet-rp

      - name: Ensure Docker on remote
        run: |
          ssh "${{ secrets.RP_CONNECTION_STRING }}" \
            "command -v docker >/dev/null || apt-get update && apt-get install -y docker.io docker-compose"

      - name: Deploy containers
        run: |
          ssh "${{ secrets.RP_CONNECTION_STRING }}" << 'EOF'
            cd /srv/miet-rp
            docker-compose pull
            docker-compose up -d
            docker-compose exec nginx nginx -s reload
          EOF
